version: "3"

services:
    feed-consumer:
        container_name: feed-consumer
        image: social/feed-consumer
        restart: always
        ports:
            - "8092:8092"
        depends_on:
            - redis
            - rabbit
            - migration-profile
            - migration-slave1
            - migration-slave2
        env_file:
            - env/common.env
            - env/jwt.env
            - env/rabbit.env
            - env/database.env
            - env/server_profile.env
        environment:
            - MYSQL_DB_HOST=db
            #- SLAVES=otus_social_slave:otus_social_passwd@tcp(db-slave1:3306)/otus_social?parseTime=true|otus_social_slave:otus_social_passwd@tcp(db-slave2:3306)/otus_social?parseTime=true
            - REDIS_URL=redis:6379
            - RABBITMQ_HOST=rabbit
        networks:
            - otus-social-network
