CREATE USER IF NOT EXISTS 'exporter'@'%' IDENTIFIED BY 'password' WITH MAX_USER_CONNECTIONS 3;
GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO 'exporter'@'%';

GRANT REPLICATION SLAVE ON *.* TO "otus_social_slave"@"%" IDENTIFIED BY "otus_social_passwd"; FLUSH PRIVILEGES;

FLUSH PRIVILEGES;